//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonappio.Areas.Account.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FirmID { get; set; }
        public Nullable<bool> IsViewed { get; set; }
        public Nullable<bool> IsReaded { get; set; }
        public string Text { get; set; }
        public string URL { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
